include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true

linter:
  rules:
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unawaited_futures
