name: ui
publish_to: 'none'
version: 1.0.0+1

environment:
  # Keep it in stable version, to avoid issues with Firebase hosting.
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.14
  google_sign_in: ^6.2.2
  http: ^1.2.2
  url_launcher: ^6.2.6
  web: ^1.1.0


dev_dependencies:
  dart_flutter_team_lints: ^3.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
